### ISSUE TITLE
Template does not work when using a single control-plane node

### ISSUE THREAD

**Issue by jp83** [k8s-at-home/template-cluster-k3s#115]
# Details

**What steps did you take and what happened:**

I'm getting back to rebuilding my cluster and thought I'd try working through this template and adopt the k8s-at-home opinions.  I'll keep debugging on my own but thought I'd document this as I believe I followed the readme verbatim and encountered this issue.  I setup 2 fresh ubuntu server node VMs and defined them as _0 and _1 ansible hosts in the .config.env with only the first being control node = True.

TASK [xanmanning.k3s : Check the conditions when a single controller is defined] ***************************************************************************************************************************************************
fatal: [k8s-0]: FAILED! => changed=false
  assertion: (k3s_etcd_datastore is not defined or not k3s_etcd_datastore)
  evaluated_to: false
  msg: Control plane configuration is invalid. Please see notes about k3s_control_node and HA in README.md.
skipping: [k8s-1]

**What did you expect to happen:**

I hoped to install k3s and bootstrap the cluster moving on to the next steps.

**Anything else you would like to add:**

2 other minor onboarding points to mention for ease of use:

This warning several times when running ./configure.sh
[PGP]	 WARN[0000] Deprecation Warning: GPG key fetching from a keyserver within sops will be removed in a future version of sops. See https://github.com/mozilla/sops/issues/727 for more information.

I had already defined my own hostnames I wanted on the nodes and noticed that it automatically changed them to hardcoded k8s-0,1,....  I was going to change them back in the inventory but noticed they were also used elsewhere like in the sops yml (provision/ansible/inventory/host_vars/k8s-0.sops.yml).

**Additional Information:**

**Comment by jp83** [comment]
The checks seem to be enforcing > 3 control plane nodes with internal etcd.  This makes sense but saw that you had just a master and worker node in your example.  I found I can move on by setting k3s_use_unsupported_config: true in ./provision/ansible/inventory/group_vars/kubernetes/k3s.yml.  Hopefully I can still figure out how to expand it later and get back to a supported config.  Maybe this documentation will help somebody else searching, you can close if you feel this is sufficient.  Thanks.

**Comment by parsec** [comment]
Thanks for this! I had the exact same problem. I wasn't expecting the setup to want all three nodes to be control plane nodes. With k3s I don't think there's really any reason _not_ to do it that way, but I wasn't entirely sure.

**Comment by onedr0p** [comment]
Docs added in https://github.com/k8s-at-home/template-cluster-k3s/commit/85a26f67fc77455373927ddb2b384691a1867573
