### ISSUE TITLE
Disable Local-Path Provisioner

### ISSUE THREAD

**Issue by PrymalInstynct** [k8s-at-home/template-cluster-k3s#120]
# Details

k3s by default will enable the local-path-provisioner and set it as the default storage class, if any other storage class is added after install such as nfs-subdir-external-provisioner or longhorn you will have to disable local-path as the default storage class each time k3s is restarted.

**Anything else you would like to add:**

The local-path-provisioner manifest lives here `/var/lib/rancher/k3s/server/manifests/local-storage.yaml` and the recommended way to disable this provisioner is by using the `--disable local-storage` option when install k3s. Then the local-storage-provisioner helm chart can be added the cluster after the fact if it is still needed.  https://github.com/rancher/local-path-provisioner/blob/master/deploy/chart/README.md#installing-the-chart

**Additional Information:**

**Comment by 5thsymphony** [comment]
If you already have a cluster setup would changing this variable and rerunning the ansible scripts be enough or would you need to tear down the whole cluster?

**Comment by onedr0p** [comment]
> If you already have a cluster setup would changing this variable and rerunning the ansible scripts be enough or would you need to tear down the whole cluster? If no good upgrade path from local storage it might be worth a note somewhere.

That should work, if you're going to disable the local storage provisioner make sure nothing is using it sand you delete all the PV and PVCs.

**Comment by PrymalInstynct** [comment]
closing issue
