### ISSUE TITLE
Renovate: Dependency Lookup Warnings

### ISSUE THREAD

**Issue by hbokh** [k8s-at-home/template-cluster-k3s#13]
# Details

After its first run, the onboarding PR by Renovate "complains" about `dependency adrienverge/yamllint.git`.

See https://github.com/k8s-at-home/template-cluster-k3s/blob/main/.pre-commit-config.yaml#L3

Looks like the `.git` extension can be safely removed on line 3.\
Works on my machine.

**Additional Information:**

Renovate warning in the PR:
```
---

### ⚠️ Dependency Lookup Warnings ⚠️

Please correct - or verify that you can safely ignore - these lookup failures before you merge this PR.

-   `Failed to look up dependency adrienverge/yamllint.git`

Files affected: `.pre-commit-config.yaml`


---
```

**Comment by onedr0p** [comment]
Oh interesting, I wonder if this is a new change in renovate.

Fixed in https://github.com/k8s-at-home/template-cluster-k3s/commit/8759c15800b9fd4d87a6b1095fa965a42528bf24
