### ISSUE TITLE
Integrate server hardening collection

### ISSUE THREAD

**Issue by mrueg** [k8s-at-home/template-cluster-k3s#137]
**Describe the solution you'd like:**

https://github.com/dev-sec/ansible-collection-hardening provides "battle tested hardening for Linux, SSH, nginx, MySQL".
It might be a good idea to include this optionally in here so users of the template don't forget to harden their system.

**Comment by onedr0p** [comment]
Hi @mrueg this project is really a start for people to get familiar with the tools we use here like k3s, flux, ansible and terraform. It might be better to suggest people to implement this themselves.

**Comment by mrueg** [comment]
Understood that you want to keep the scope of this project limited. What would be a good solution? Pointing to it in the readme? Having another task in the Taskfile?

**Comment by onedr0p** [comment]
Maybe a mention at the bottom of the Readme near other things that are mentioned people can do afterwards.
