### ISSUE TITLE
Investigate support for age as an alternative for gnupg

### ISSUE THREAD

**Issue by mrueg** [k8s-at-home/template-cluster-k3s#152]
# Details

**Describe the solution you'd like:**

Replace the dependency on gnupg by age https://github.com/FiloSottile/age https://nixfaq.org/2021/01/age-the-modern-alternative-to-gpg.html

Supported by sops already: https://github.com/mozilla/sops/pull/688
Here's a discussion on flux2: https://github.com/fluxcd/flux2/discussions/770
Docs: https://fluxcd.io/docs/components/kustomize/kustomization/#age

**Comment by onedr0p** [comment]
I am in the process of migrating my repo over to age. Looks like ansible, terraform and sops-vscode seem to work just fine.

https://github.com/onedr0p/home-cluster/commit/d1e4dda92fe063ac7e5d278ecd8c175bc64887f2

**Comment by onedr0p** [comment]
@mrueg please give me a review. https://github.com/k8s-at-home/template-cluster-k3s/pull/153

Thanks!
