### ISSUE TITLE
invalid downgrade; server version is lower than determined cluster version

### ISSUE THREAD

**Issue by nickyhuyskens** [k8s-at-home/template-cluster-k3s#159]
# Details

**What steps did you take and what happened:**
I followed all instructions from the readme on a fresh installed ubuntu server 20.04.3 lts and after a reboot, kubernetes won't start.
journalctl -xe gives the following:

Dec 06 15:14:27 k8s-0 k3s[5219]: {"level":"fatal","ts":"2021-12-06T15:14:27.709Z","caller":"membership/cluster.go:790","msg":"invalid downgrade; server version is lower than determined cluster version","current-server-version":"3.4.13","determined-cluster-version":"3.5","stacktrace":"github.com/rancher/k3s/vendor/go.>

I tried from a fresh install twice, got the same results.

**What did you expect to happen:**
I expect kubernetes to be able to start after a reboot

**Comment by onedr0p** [comment]
Make sure the system upgrade controller is using the 1.22 release. There was a fix pushed recently to those files.

**Comment by onedr0p** [comment]
https://github.com/k8s-at-home/template-cluster-k3s/commit/6c5019ee6ccfadaa0c2566357d61ff19355d2393

**Comment by nickyhuyskens** [comment]
I had those changes already pulled in

**Comment by nickyhuyskens** [comment]
Sorry, I found out that I was still referring to an old repo in my .config.env file which did not have that update yet! Thanks a lot for the quick response!
