### ISSUE TITLE
Renovate Configuration

### ISSUE THREAD

**Issue by hbokh** [k8s-at-home/template-cluster-k3s#16]
# Details

Whenever I use the `renovate.json5` from this template, I get this issue from `renovate-bot`:

---

There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Location: `renovate.json5`
Error type: The renovate configuration file contains some invalid settings
Message: `packageRules[1]: packageRules cannot combine both matchUpdateTypes and separateMinorPatch. Rule: {"matchDatasources":["docker"],"enabled":true,"commitMessageTopic":"container image {{depName}}","commitMessageExtra":"to {{#if isSingleVersion}}v{{{newVersion}}}{{else}}{{{newValue}}}{{/if}}","matchUpdateTypes":["major","minor","patch"],"separateMinorPatch":true}`

---

When line 45 is commented (`// "separateMinorPatch": true`)
https://github.com/k8s-at-home/template-cluster-k3s/blob/main/.github/renovate.json5#L45
things are OK.

I wonder is the file `renovate.json5` in this repo "wrong" or am I in error somewhere? TIA!

**Comment by onedr0p** [comment]
Very strange, renovate is enabled for this repo and it's not complaining of that issue. It still seems to work fine here 🤔

**Comment by hbokh** [comment]
FWIW I'm using the _Self-Hosting Renovate_ with the `renovate/renovate:slim` Docker image, updated today to `"renovateVersion": "25.9.0"`.
Maybe the  _GitHub app installation_ behaves different..?

**Comment by onedr0p** [comment]
Wouldn't surprise me, they do release breaking changes quite often. However the free SaaS version does mitigate this by migrating the configuration to newer version before it runs.

**Comment by hbokh** [comment]
Right. I've also asked in `renovatebot / renovate` discussions:
https://github.com/renovatebot/renovate/discussions/9850

**Comment by hbokh** [comment]
Answered in the discussions: https://github.com/renovatebot/renovate/discussions/9850#discussioncomment-695034
