### ISSUE TITLE
Should cluster-settings.yaml be encrypted with SOPS?

### ISSUE THREAD

**Issue by pgrauman** [k8s-at-home/template-cluster-k3s#176]
# Details
The README makes references to a `./cluster/base/cluster-settings.sops.yaml` file but configure.sh does not encrypt `./cluster/base/cluster-settings.yaml`. Do you recommend encrypting this yaml? The variables in there post initialization do not seem concerning.

I learned a lot from the repo, thank you for maintaining it.

**Comment by onedr0p** [comment]
Nope, those are meant to be clear text.

**Comment by pgrauman** [comment]
Thanks @onedr0p

**Comment by mrueg** [comment]
@onedr0p so as @pgrauman was mentioning, https://github.com/k8s-at-home/template-cluster-k3s/blame/main/README.md#L234 should be changed from `./cluster/base/cluster-settings.sops.yaml`to `./cluster/base/cluster-settings.yaml` then?

**Comment by onedr0p** [comment]
Right that's a typo
