### ISSUE TITLE
Anonymous-Auth=true still required?

### ISSUE THREAD

**Issue by mrueg** [k8s-at-home/template-cluster-k3s#177]
I was reviewing the default settings and wondering if this is still required? It mentions haproxy, but i believe this was never used in this project
https://github.com/k8s-at-home/template-cluster-k3s/blob/main/provision/ansible/inventory/group_vars/master/k3s.yml#L49

```
  # Required for HAProxy health-checks
  kube-apiserver-arg:
    - "anonymous-auth=true" 
```

**Comment by onedr0p** [comment]
Not required, but doesn't hurt to enable it if people wanted to use HAProxy as a external LB for kube API

**Comment by mrueg** [comment]
Okay, I was wondering as CIS benchmarks recommend against it (although they don't score it if it's enabled), see also: https://rancher.com/docs/k3s/latest/en/security/self_assessment/#1-2-1

**Comment by onedr0p** [comment]
Makes sense, but I am not too concerned about security as this project is more oriented towards running this all at home where we are usually more relaxed on certain aspects of security.

**Comment by mrueg** [comment]
Gotcha, I can still remove it in my fork. Thanks for the quick answer on this topic! :+1:
