### ISSUE TITLE
Add documentation for a single node cluster

### ISSUE THREAD

**Issue by mrueg** [k8s-at-home/template-cluster-k3s#178]
**Describe the solution you'd like:**

For starters using this project it might be easiest to run this on a single node to become familiar with it.
The README could be extended to describe what they'd need to do in order to run it on a single node (e.g. specific settings around control plane, simplifying networking, etc.)

**Comment by onedr0p** [comment]
I'm not against it, having more options present to the user might be a good or bad thing haha.

**Comment by onedr0p** [comment]
And added in https://github.com/k8s-at-home/template-cluster-k3s/commit/85a26f67fc77455373927ddb2b384691a1867573
