### ISSUE TITLE
Where is ansible var {{ kubevip_interface }} declared?

### ISSUE THREAD

**Issue by ahgraber** [k8s-at-home/template-cluster-k3s#185]
I'm trying to follow along with the ansible provisioning of the cluster.  I can see that `k3s_registration_address` is being brought in `group_vars/kubernetes/k3s.yaml` file, but I don't see `kubevip_interface` declared anywhere.  

I can see we declare it as `BOOTSTRAP_ANSIBLE_KUBE_VIP_INTERFACE` in config.env, and that is picked up in [global kube-vip template](https://github.com/k8s-at-home/template-cluster-k3s/blob/main/tmpl/cluster/kube-vip-daemonset.yaml), but I can't trace the lineage into the [ansible template file](https://github.com/k8s-at-home/template-cluster-k3s/blob/main/provision/ansible/playbooks/templates/kube-vip-daemonset.yaml.j2)

Am I missing something?

https://github.com/k8s-at-home/template-cluster-k3s/blob/088c1d9bcf622ce6e522958d106a02b3b15de95d/provision/ansible/playbooks/templates/kube-vip-daemonset.yaml.j2#L41

**Comment by onedr0p** [comment]
That is used in this file https://github.com/k8s-at-home/template-cluster-k3s/blob/main/tmpl/cluster/kube-vip-daemonset.yaml which gets copied into the right place when you run the configure script.

**Comment by ahgraber** [comment]
Why have two template files for kube-vip?  Is one for k3s init and the other used once flux is installed or something?

**Comment by onedr0p** [comment]
Yes, I was just writing that 

Basically kube vip is installed with k3s at install time and then managed by flux afterwards
