### ISSUE TITLE
Error while running precommit

### ISSUE THREAD

**Issue by Stoffe** [k8s-at-home/template-cluster-k3s#192]
Im getting an error trying to run the first command task pre-commit:init
Running on an ubuntu and I checked that python-Levenshtein-wheels is installed and to my knowledge the prereqs are installed...
The question is, is it because Im using the newest version of everything and I see some deprecated error in the logs? or wrong version of python? (but no version is specified in the readme)

Trying to figure out what the problem might be here...

-------------------------------------------------------
`
An unexpected error has occurred: CalledProcessError: command: ('/home/[USER]/.cache/pre-commit/repobbmtfqhw/py_env-default/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/[USER]/.cache/pre-commit/repobbmtfqhw
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting fuzzywuzzy
      Using cached fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
    Collecting python-Levenshtein-wheels
      Using cached python-Levenshtein-wheels-0.13.2.tar.gz (38 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Building wheels for collected packages: pre-commit-hooks, python-Levenshtein-wheels
      Building wheel for pre-commit-hooks (setup.py): started
      Building wheel for pre-commit-hooks (setup.py): finished with status 'done'
      Created wheel for pre-commit-hooks: filename=pre_commit_hooks-1.1.10-py3-none-any.whl size=12935 sha256=53cbbea1b01fe2dc92cddd95719a6a81f48fab2d0c93623b2b3c780885965c58
      Stored in directory: /tmp/pip-ephem-wheel-cache-38rrpw4b/wheels/69/55/9a/7edb989d561af202c6fb115bb4cb89090e30146869784f82c6
      Building wheel for python-Levenshtein-wheels (setup.py): started
      Building wheel for python-Levenshtein-wheels (setup.py): finished with status 'error'
      Running setup.py clean for python-Levenshtein-wheels
    Successfully built pre-commit-hooks
    Failed to build python-Levenshtein-wheels
    Installing collected packages: python-Levenshtein-wheels, fuzzywuzzy, pre-commit-hooks
        Running setup.py install for python-Levenshtein-wheels: started
        Running setup.py install for python-Levenshtein-wheels: finished with status 'error'
    
stderr:
      ERROR: Command errored out with exit status 1:
       command: /home/[USER]/.cache/pre-commit/repobbmtfqhw/py_env-default/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bv001b0l/python-levenshtein-wheels_c9212f793da746af91729b824755bdb2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bv001b0l/python-levenshtein-wheels_c9212f793da746af91729b824755bdb2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hlc8bxfo
           cwd: /tmp/pip-install-bv001b0l/python-levenshtein-wheels_c9212f793da746af91729b824755bdb2/
      Complete output (14 lines):
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/Levenshtein
      copying Levenshtein/StringMatcher.py -> build/lib.linux-x86_64-3.10/Levenshtein
      copying Levenshtein/__init__.py -> build/lib.linux-x86_64-3.10/Levenshtein
      running build_ext
      building 'Levenshtein._levenshtein' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/Levenshtein
      gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/[USER]/.cache/pre-commit/repobbmtfqhw/py_env-default/include -I/home/linuxbrew/.linuxbrew/opt/python@3.10/include/python3.10 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-3.10/Levenshtein/_levenshtein.o
      error: command 'gcc-5' failed: No such file or directory
      ----------------------------------------
      ERROR: Failed building wheel for python-Levenshtein-wheels
        ERROR: Command errored out with exit status 1:
         command: /home/[USER]/.cache/pre-commit/repobbmtfqhw/py_env-default/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bv001b0l/python-levenshtein-wheels_c9212f793da746af91729b824755bdb2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bv001b0l/python-levenshtein-wheels_c9212f793da746af91729b824755bdb2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gvg2lees/install-record.txt --single-version-externally-managed --compile --install-headers /home/[USER]/.cache/pre-commit/repobbmtfqhw/py_env-default/include/site/python3.10/python-Levenshtein-wheels
             cwd: /tmp/pip-install-bv001b0l/python-levenshtein-wheels_c9212f793da746af91729b824755bdb2/
        Complete output (16 lines):
        running install
        /home/[USER]/.cache/pre-commit/repobbmtfqhw/py_env-default/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-3.10
        creating build/lib.linux-x86_64-3.10/Levenshtein
        copying Levenshtein/StringMatcher.py -> build/lib.linux-x86_64-3.10/Levenshtein
        copying Levenshtein/__init__.py -> build/lib.linux-x86_64-3.10/Levenshtein
        running build_ext
        building 'Levenshtein._levenshtein' extension
        creating build/temp.linux-x86_64-3.10
        creating build/temp.linux-x86_64-3.10/Levenshtein
        gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/[USER]/.cache/pre-commit/repobbmtfqhw/py_env-default/include -I/home/linuxbrew/.linuxbrew/opt/python@3.10/include/python3.10 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-3.10/Levenshtein/_levenshtein.o
        error: command 'gcc-5' failed: No such file or directory
        ----------------------------------------
    ERROR: Command errored out with exit status 1: /home/[USER]/.cache/pre-commit/repobbmtfqhw/py_env-default/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bv001b0l/python-levenshtein-wheels_c9212f793da746af91729b824755bdb2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bv001b0l/python-levenshtein-wheels_c9212f793da746af91729b824755bdb2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gvg2lees/install-record.txt --single-version-externally-managed --compile --install-headers /home/[USER]/.cache/pre-commit/repobbmtfqhw/py_env-default/include/site/python3.10/python-Levenshtein-wheels Check the logs for full command output.

`

**Comment by onedr0p** [comment]
This is likely an issue with pre-commit and your environment.

**Comment by JOduMonT** [comment]
@Stoffe I'm curious about how did you installed pre-commit ??
Personally, I use Debian 11 and installed it inside a virtualenv with pip under Python3.
