### ISSUE TITLE
Why not ArgoCD?

### ISSUE THREAD

**Issue by olegstepura** [k8s-at-home/template-cluster-k3s#197]
# Details

Hi guys! I understand that this is "highly opinionated template" and as a non-devops guy I could learn a lot from it.

But please let me ask why not `ArgoCD` instead of `Flux2` for home users?

Background: I'm not anyhow affiliated with `ArgoCD`, and might miss some obvious disadvantages of using it. And I'm still in the process of building my home k8s cluster. After a brief overview it looks like `Argo CD` might be better fitting for home users since it provides a nice Web UI with a clear picture, making it easier to debug what is going on in your cluster.

I would appreciate any feedback. Thanks!

**Comment by onedr0p** [comment]
I don't think it's Flux or Argo.  Both have their strengths and weaknesses. I always had a plan to create another template with some opinionated way to install and configure ArgoCD, or maybe someone from the community can do this as well.

**Comment by olegstepura** [comment]
Which one would you choose to start such template from the beginning for the time being?

**Comment by onedr0p** [comment]
Try Flux, if your feel like using the cli is too much effort switch to Argo?

**Comment by olegstepura** [comment]
Ok, thanks. Closing.
