### ISSUE TITLE
Provide Cilium as an alternative to Calico

### ISSUE THREAD

**Issue by mrueg** [k8s-at-home/template-cluster-k3s#204]
# Details

Have Cilium as a networking alternative to Calico.
https://github.com/cilium/cilium

**Additional Information:**

The implementation could look similar:
https://github.com/0dragosh/homelab-k3s/commit/6889c091dd69984fabc2ba9424c11a75c7570494

**Comment by onedr0p** [comment]
Building more options into this template repo is going to make it hard to test, I'm not against it but having a single option (cilium or calico) is probably best.

**Comment by mrueg** [comment]
Agree, migration to Cilium might work as well. I didn't want to make it sound like it's without alternative. :)

**Comment by onedr0p** [comment]
Closing this issue, if someone would like to open a PR to add cilium I will definitely consider it. Cilium has a helm chart, it could be implemented with the k3s `HelmChart` CRD via Ansible and then taken over by flux to manage it.
