### ISSUE TITLE
Issues with kubevip not deploying

### ISSUE THREAD

**Issue by Mixie-12** [k8s-at-home/template-cluster-k3s#211]
Hi,
So the kube-vip containers fails to start, and gives the following error:
Input:
`k3s kubectl logs kube-vip-c2wvw --namespace kube-system`
Output:
`level=fatal msg="lo  is not valid interface, reason: get lo  failed, error: Link not found"
`

lo exists on the node, I also tried  different interfaces with non of them working.

What am I missing?

**Comment by Mixie-12** [comment]
I dont know why, but the .config.env file is adding a space to the name, causing the error.  Hardcoding it worked.

**Comment by onedr0p** [comment]
@Mixie-12 can you explain your problem and how you fixed it a bit more in detail, I'm not following. Thanks

**Comment by Mixie-12** [comment]
So the .config.env requries the following variable:

BOOTSTRAP_ANSIBLE_KUBE_VIP_INTERFACE (The network interface on the host kube-vip should attach to)

I fill in interface name, run the ./config, and starts the provisioning.
But kubevip fails to start, saying the interface (eth1) does not exist.
I notice the interface name in the error logs in kubectl has an extra  space in it.
After replacing BOOTSTRAP_ANSIBLE_KUBE_VIP_INTERFACE with my interface in [kube-vip-daemonset.yaml](https://github.com/k8s-at-home/template-cluster-k3s/blob/655a6da9f5bd96e7d03534528b432d5ec7901c99/tmpl/cluster/kube-vip-daemonset.yaml) and [kube-vip.yml](https://github.com/k8s-at-home/template-cluster-k3s/blob/8d5516a5462cd757c10d1e26e5edc07bd5630304/tmpl/ansible/kube-vip.yml), i got it working.

**Comment by onedr0p** [comment]
hm odd, maybe you had an extra space in `BOOTSTRAP_ANSIBLE_KUBE_VIP_INTERFACE`?

e.g. you might have had

`BOOTSTRAP_ANSIBLE_KUBE_VIP_INTERFACE ="eth1<space>"`
