### ISSUE TITLE
Need help to start

### ISSUE THREAD

**Issue by JOduMonT** [k8s-at-home/template-cluster-k3s#215]
# context
Hi;

I'm totally a newbie with kubernetes, but not with docker/docker-compose/VM/...

I tried to login to Discord but I'm unable to see the hCaptcha, so I came back here....

**Ask your question:**
- What is the most straight forward way to make it happen, I means
- What is the minimum number of host required ?
I though with k3s is was 1

I figure I need a kinds of Unix/Linux compatible system sonInisntalled in a VM with Ubuntu 20.04LTS as my controller/workstation where I installed Python3, Ansible, Pre-Commit, VSCode, Age, GoLang, and integrated direnv in my .bashrc and clone the repo, but....

- My system say  task is not a command when I run `task pre-commit:init` but pre-commit command did something :p

### Moving the Section config higher in the Wiki
Logically; I believe the section https://github.com/k8s-at-home/template-cluster-k3s#page_facing_up-configuration should before https://github.com/k8s-at-home/template-cluster-k3s#closed_lock_with_key-setting-up-age so in that case hopefully others peoplee suppose to started with
> BOOTSTRAP_AGE_PUBLIC_KEY ??
> should it continue with = then my agekey ??

Sorry  for the mess, I'm currently working remotely from a smartphone :p

PS: I'm very keen to help that project to become better even if it look already awesome!!

**Comment by onedr0p** [comment]
> What is the minimum number of host required?

You can run a single node k3s cluster but if going more than that it's suggested to use 3 control plane nodes for proper HA.

> My system say task is not a command when I run task pre-commit:init but pre-commit command did something 

You probably don't have [task](https://github.com/go-task/task) installed or it is no in your `$PATH`

> Logically; I believe the section ...

The reason AGE section is before the Configuration section is that you need to fill out the `BOOTSTRAP_AGE_PUBLIC_KEY` which you will only get by completing the AGE section first.

**Comment by JOduMonT** [comment]
So I worked on a real computer today, not via my smartphone and I wrote those notes about how to install the requirement.
I'm running Debian SID, which is compatible with Ubuntu Focal

> # git AS ROOT
> `apt install -y git`
> 
> # Ansible AS ROOT
> ## https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-and-upgrading-ansible-with-pip
> ````bash
> echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu focal main" > /etc/apt/sources.list.d/ansible.list
> apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
> apt update
> apt install -y ansible
> ````
> ## OR INSTALL IT AS USER
> ````bash
> sudo apt install -y curl python3
> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> python3 get-pip.py --user
> python3 -m pip install --user ansible
> ````
> 
> # dirEnv AS ROOT
> ## https://github.com/direnv/direnv/blob/master/docs/installation.md
> `curl -sfL https://direnv.net/install.sh | bash`
> ## OR for Debian/Ubuntu AS ROOT
> `apt install -y direnv`
> 
> # flux AS ROOT
> ## https://fluxcd.io/docs/installation/
> `curl -s https://fluxcd.io/install.sh | bash`
> 
> # age AS ROOT
> ## https://github.com/FiloSottile/age#installation
> `apt install -y age`
> 
> # task
> ## https://github.com/go-task/task/releases
> ````bash
> wget -O /tmp/task.deb https://github.com/go-task/task/releases/download/v3.10.0/task_linux_amd64.deb
> dpkg -i /tmp/task.deb
> ````
> 
> # ipcalc AS ROOT
> `apt install -y ipcalc`
> 
> # ipcalc AS ROOT
> `apt install -y ipcalc jq`
> 
> # kubectl AS ROOT
> ````bash
> apt update
> apt install -y apt-transport-https ca-certificates curl
> curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
> echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" > etc/apt/sources.list.d/kubernetes.list
> apt update
> apt install -y kubectl
> ````
> ## OR INSTALL IT AS USER
> ````bash
> curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
> chmod +x kubectl
> mkdir -p ~/.local/bin/kubectl
> mv ./kubectl ~/.local/bin/kubectl
> # and then append (or prepend) ~/.local/bin to $PATH
> ````
> 
> # sops
> ## https://github.com/mozilla/sops/releases
> ### required GoLang AS ROOT
> ````bash
> wget https://go.dev/dl/go1.17.6.linux-amd64.tar.gz
> rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.6.linux-amd64.tar.gz
> ````
> ## AS ROOT
> ````bash
> wget -O /tmp/sops.deb https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb
> dpkg -i /tmp/sops.deb
> ````
> 
> # terraform AS ROOT
> ````bash
> curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
> apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
> apt update
> apt install -y terraform
> ````
> ## OR with DEBIAN TESTING/SID
> ````bash
> curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
> echo "deb [arch=amd64] https://apt.releases.hashicorp.com focal main" > /etc/apt/sources.list.d/hashicorp.list
> apt update
> apt install -y terraform
> ````

@onedr0p do you think those notes could be useful in the wifki ?
and yes if; *I'll polish them* — but where I should integrate them ?

**Comment by onedr0p** [comment]
I appreciate the thought but not everyone uses Linux (or Debian) and it's probably best to point to the official docs on how to install and/or configure these tools.

Most methods of installation are easily figured out in a "hour to install tool x on y OS" and I really think people should be able to figure that part out.
