### ISSUE TITLE
Option to integrate ufw or other firewall rules

### ISSUE THREAD

**Issue by step21** [k8s-at-home/template-cluster-k3s#222]
# Details

**Describe the solution you'd like:**

A template or other method to integrate ufw rules. 

**Anything else you would like to add:**

Before using this template I added ufw on the machine(s). Then, I either need to manually fix ufw on each machine, or write custome templates / scripts. Ideally, for each step  such as installing k3s, there would be the option to open the relevant ports.

**Additional Information:**

**Comment by step21** [comment]
That's my fear. I am only just learning so I might not be the best person for this. The hardening repo linked in the readme sets some ufw defaults, but does not cover specific ports.

**Comment by step21** [comment]
Ok, thanks! Today I also don't have time, but will do a PR soon hopefully.

**Comment by onedr0p** [comment]
Going to close this issue, feel free to open a PR if you have time.
