### ISSUE TITLE
Ansible Ubuntu Prepare playbook Raspberry Pi check tasks throw fatal error

### ISSUE THREAD

**Issue by mattsoldo** [k8s-at-home/template-cluster-k3s#251]
# Details

**What steps did you take and what happened:**

Running `task ansible:playbook:ubuntu-prepare`, all steps of setup working fine prior. Using this with nodes that are *not* Raspberry Pis.

**What did you expect to happen:**

Expected Raspberry Pi check run successfully to show that nodes are no Pis.

**Anything else you would like to add:**

**Additional Information:**

Output:

````
TASK [ubuntu : Check if Raspberry Pi] ***************************************************************************************************************************************************
fatal: [k8s-2]: FAILED! => changed=true 
  cmd:
  - grep
  - -q
  - Raspberry Pi
  - /proc/cpuinfo
  delta: '0:00:00.019747'
  end: '2022-03-06 21:54:00.526425'
  msg: non-zero return code
  rc: 1
  start: '2022-03-06 21:54:00.506678'
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring
fatal: [k8s-0]: FAILED! => changed=true 
  cmd:
  - grep
  - -q
  - Raspberry Pi
  - /proc/cpuinfo
  delta: '0:00:00.020600'
  end: '2022-03-06 21:54:00.622424'
  msg: non-zero return code
  rc: 1
  start: '2022-03-06 21:54:00.601824'
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring
fatal: [k8s-1]: FAILED! => changed=true 
  cmd:
  - grep
  - -q
  - Raspberry Pi
  - /proc/cpuinfo
  delta: '0:00:00.019085'
  end: '2022-03-06 21:54:00.632873'
  msg: non-zero return code
  rc: 1
  start: '2022-03-06 21:54:00.613788'
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring

````

**Comment by onedr0p** [comment]
If you run that grep command directly on the hosts what is the output?

**Comment by mattsoldo** [comment]
The grep command produces no output:

````
soldo@k8s-1:~$ grep -q  "Raspberry Pi" /proc/cpuinfo
soldo@k8s-1:~$ grep "Raspberry Pi" /proc/cpuinfo
soldo@k8s-1:~$ 
````

**Comment by onedr0p** [comment]
Very interesting, that should gracefully error... Maybe comment out this code so it works, it try to debug it. I haven't had any other reports of this issue happening so I'm curious what's causing it. If you find it out please feel free to open a PR with a fix. Thanks!

https://github.com/k8s-at-home/template-cluster-k3s/blob/main/provision/ansible/roles/ubuntu/tasks/packages.yml#L40-L57

**Comment by onedr0p** [comment]
Going to close this issue, please reopen if you're still stuck.

**Comment by Ben-Hampson** [comment]
I had the exact same issue on an Ubuntu 22.04 LTS VM.

```
TASK [ubuntu : Check if Raspberry Pi] ************************************************************************************************
fatal: [k8s-0]: FAILED! => changed=true 
  cmd:
  - grep
  - -q
  - Raspberry Pi
  - /proc/cpuinfo
  delta: '0:00:00.003110'
  end: '2022-04-30 20:59:34.763862'
  msg: non-zero return code
  rc: 1
  start: '2022-04-30 20:59:34.760752'
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring

TASK [ubuntu : Install raspberry specific packages for Ubuntu 21 or greater] *********************************************************
FAILED - RETRYING: [k8s-0]: Install raspberry specific packages for Ubuntu 21 or greater (5 retries left).
FAILED - RETRYING: [k8s-0]: Install raspberry specific packages for Ubuntu 21 or greater (4 retries left).
FAILED - RETRYING: [k8s-0]: Install raspberry specific packages for Ubuntu 21 or greater (3 retries left).
FAILED - RETRYING: [k8s-0]: Install raspberry specific packages for Ubuntu 21 or greater (2 retries left).
FAILED - RETRYING: [k8s-0]: Install raspberry specific packages for Ubuntu 21 or greater (1 retries left).
fatal: [k8s-0]: FAILED! => changed=false 
  attempts: 5
  msg: No package matching 'linux-modules-extra-raspi' is available
```

ssh-ing in and running the `grep` returns nothing.

**Comment by onedr0p** [comment]
Seems like something might have changed with 22.04, as `No package matching 'linux-modules-extra-raspi' is available`

Maybe it was changed to this package?

https://launchpad.net/ubuntu/jammy/+source/linux-raspi

**Comment by onedr0p** [comment]
I have _fixed_ this issue, meaning the code doesn't exist anymore for this check or installing linux-modules-extra-raspi. If anyone has an idea if this is still needed on 22.04, please open a PR 🙏🏼

**Comment by onedr0p** [comment]
Ok, after some confirmation I believe this is really fixed. https://github.com/k8s-at-home/template-cluster-k3s/commit/d10800e962565137f324766cd2790831168e4f11

**Comment by onedr0p** [comment]
Closing issue, this should be fixed now and forever.
