### ISSUE TITLE
question on <task ansible:playbook:k3s-install>

### ISSUE THREAD

**Issue by fabricesemti80** [k8s-at-home/template-cluster-k3s#255]
Hopefully a quick and simple question:

- I have a current 4 node cluster that I deployed using this template
- I plan to add another node (slightly different hardware, mainly to improve Plex experience) to the cluster
- If I installed Ubuntu and added the node's details to the env file plus configured it's nic according the docs, can I just re-run the ansible playbook, to add the new node?
 (It will not affect the existing cluster nodes correct? So the cluster will be uneffected, and only the new node will change...?)

**Comment by onedr0p** [comment]
Probably best to just add the new host to the ansible hosts file and create the host secret in the host vars and make sure ansible is installing the same k3s version that's installed. Then you can rerun the playbook.

**Comment by fabricesemti80** [comment]
Thanks. Pretty much that is what I had in mind.
