### ISSUE TITLE
Stuck at ssh ansible

### ISSUE THREAD

**Issue by Haasie** [k8s-at-home/template-cluster-k3s#309]
Hello,

Im just a starter wo want to explorer Kubernetes and make it core for my home lab.

I forked the template and have installed al prerequisites.
If filed in the .config.env file with my variables.
When i run the config.sh --verify it keep saying that it can not connect to the ansible host via ssh.
I've double checked the username and password and they work when ssh trough the terminal. Due the limited info from the error, i do not know where to look further.

Can someone please gave me guidance where to look?

Thank you

**Comment by onedr0p** [comment]
Issue appeared to be the SSH key wasn't copied over to the hosts.
